version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: produtos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: trabDocker
    ports:
      - "5432:5432"
  web:
    image: trabdocker
    ports:
      - "8080:8080"
    depends_on:
      - db
